import type {
  MockUser,
  OnboardingRecord,
  Approval,
  ActivityEntry,
  Report,
  DigitalEmployee,
  DashboardMetrics,
} from "./types";

export const DEMO_CREDENTIALS = {
  email: "demo@axiploy.com",
  password: "Axiploy2024!",
};

export const ADMIN_CREDENTIALS = {
  email: "admin",
  password: "admin",
};

export const MOCK_USER: MockUser = {
  id: "user-001",
  email: "demo@axiploy.com",
  name: "James Hartley",
  role: "client_admin",
  clientId: "client-001",
  clientName: "Pinnacle Group",
};

export const MOCK_METRICS: DashboardMetrics = {
  activeEmployees: 3,
  tasksCompleted: 428,
  hoursSaved: 74,
  pendingApprovals: 5,
  highRiskItems: 2,
  reportStatus: "Monthly report ready",
};

export const MOCK_DIGITAL_EMPLOYEES: DigitalEmployee[] = [
  {
    id: "de-001",
    clientId: "client-001",
    type: "onboarding",
    name: "AI Onboarding Assistant",
    status: "Active",
    stats: [
      { label: "Active onboardings", value: 12 },
      { label: "Missing documents", value: 5 },
      { label: "High-risk starters", value: 2 },
    ],
  },
  {
    id: "de-002",
    clientId: "client-001",
    type: "admin",
    name: "AI Admin Assistant",
    status: "Active",
    stats: [
      { label: "Emails processed", value: 38 },
      { label: "Tasks created", value: 14 },
      { label: "Reminders sent", value: 6 },
    ],
  },
  {
    id: "de-003",
    clientId: "client-001",
    type: "growth",
    name: "AI Growth Assistant",
    status: "Active",
    stats: [
      { label: "Leads found", value: 21 },
      { label: "Follow-ups due", value: 8 },
      { label: "Awaiting approval", value: 4 },
    ],
  },
];

export const MOCK_ONBOARDING: OnboardingRecord[] = [
  {
    id: "emp-001",
    clientId: "client-001",
    employeeName: "Sarah Thompson",
    role: "Site Engineer",
    department: "Engineering",
    startDate: "2026-07-07",
    manager: "David Chen",
    status: "Missing Documents",
    riskLevel: "High",
    email: "sarah.thompson@email.com",
    phone: "0412 345 678",
    missingDocuments: 3,
    lastContacted: "2026-06-26",
    nextAction: "Chase tax file number and right to work documents",
    notes: "Visa status needs verification before start date.",
    documents: [
      { id: "doc-001", name: "Signed Employment Contract", required: true, received: true, receivedAt: "2026-06-20" },
      { id: "doc-002", name: "Tax File Number Declaration", required: true, received: false },
      { id: "doc-003", name: "Right to Work Evidence", required: true, received: false },
      { id: "doc-004", name: "Bank Details Form", required: true, received: true, receivedAt: "2026-06-21" },
      { id: "doc-005", name: "Emergency Contact Form", required: false, received: false },
      { id: "doc-006", name: "Safety Induction Certificate", required: true, received: false },
    ],
    communications: [
      {
        id: "com-001",
        type: "email",
        direction: "sent",
        subject: "Welcome to Pinnacle Group — Action Required",
        body: "Hi Sarah, welcome aboard! Please complete your onboarding documents by clicking the link below.",
        timestamp: "2026-06-20T09:00:00",
      },
      {
        id: "com-002",
        type: "email",
        direction: "sent",
        subject: "Reminder: Outstanding Documents",
        body: "Hi Sarah, we still have 3 outstanding documents required before your start date. Please action as soon as possible.",
        timestamp: "2026-06-26T10:00:00",
      },
    ],
  },
  {
    id: "emp-002",
    clientId: "client-001",
    employeeName: "Marcus Rivera",
    role: "Project Manager",
    department: "Operations",
    startDate: "2026-07-14",
    manager: "Lisa Park",
    status: "In Progress",
    riskLevel: "Low",
    email: "marcus.rivera@email.com",
    phone: "0423 456 789",
    missingDocuments: 1,
    lastContacted: "2026-06-25",
    nextAction: "Awaiting signed contract",
    notes: "",
    documents: [
      { id: "doc-007", name: "Signed Employment Contract", required: true, received: false },
      { id: "doc-008", name: "Tax File Number Declaration", required: true, received: true, receivedAt: "2026-06-24" },
      { id: "doc-009", name: "Right to Work Evidence", required: true, received: true, receivedAt: "2026-06-24" },
      { id: "doc-010", name: "Bank Details Form", required: true, received: true, receivedAt: "2026-06-24" },
      { id: "doc-011", name: "Emergency Contact Form", required: false, received: true, receivedAt: "2026-06-24" },
    ],
    communications: [
      {
        id: "com-003",
        type: "email",
        direction: "sent",
        subject: "Welcome to Pinnacle Group",
        body: "Hi Marcus, we're excited to have you join the team. Please complete the attached onboarding pack.",
        timestamp: "2026-06-23T09:00:00",
      },
    ],
  },
  {
    id: "emp-003",
    clientId: "client-001",
    employeeName: "Priya Mehta",
    role: "Financial Analyst",
    department: "Finance",
    startDate: "2026-06-30",
    manager: "Tom Walsh",
    status: "At Risk",
    riskLevel: "Critical",
    email: "priya.mehta@email.com",
    phone: "0434 567 890",
    missingDocuments: 4,
    lastContacted: "2026-06-25",
    nextAction: "Urgent: Start date in 2 days, 4 documents outstanding",
    notes: "Starting Monday — immediate escalation required.",
    documents: [
      { id: "doc-012", name: "Signed Employment Contract", required: true, received: true, receivedAt: "2026-06-18" },
      { id: "doc-013", name: "Tax File Number Declaration", required: true, received: false },
      { id: "doc-014", name: "Right to Work Evidence", required: true, received: false },
      { id: "doc-015", name: "Bank Details Form", required: true, received: false },
      { id: "doc-016", name: "Safety Induction Certificate", required: true, received: false },
      { id: "doc-017", name: "Superannuation Choice Form", required: true, received: true, receivedAt: "2026-06-18" },
    ],
    communications: [
      {
        id: "com-004",
        type: "email",
        direction: "sent",
        subject: "URGENT: Documents Required Before Monday",
        body: "Hi Priya, your start date is this Monday and we still have 4 critical documents outstanding. Please action immediately.",
        timestamp: "2026-06-25T14:00:00",
      },
    ],
  },
  {
    id: "emp-004",
    clientId: "client-001",
    employeeName: "Jake Morrison",
    role: "Electrician",
    department: "Trades",
    startDate: "2026-06-16",
    manager: "Sandra Lee",
    status: "Complete",
    riskLevel: "Low",
    email: "jake.morrison@email.com",
    phone: "0445 678 901",
    missingDocuments: 0,
    lastContacted: "2026-06-14",
    nextAction: "None — onboarding complete",
    notes: "All documents received and verified.",
    documents: [
      { id: "doc-018", name: "Signed Employment Contract", required: true, received: true, receivedAt: "2026-06-10" },
      { id: "doc-019", name: "Tax File Number Declaration", required: true, received: true, receivedAt: "2026-06-10" },
      { id: "doc-020", name: "Right to Work Evidence", required: true, received: true, receivedAt: "2026-06-10" },
      { id: "doc-021", name: "Electrical Licence", required: true, received: true, receivedAt: "2026-06-10" },
      { id: "doc-022", name: "Bank Details Form", required: true, received: true, receivedAt: "2026-06-11" },
    ],
    communications: [],
  },
  {
    id: "emp-005",
    clientId: "client-001",
    employeeName: "Natalie Wong",
    role: "HR Coordinator",
    department: "Human Resources",
    startDate: "2026-07-21",
    manager: "David Chen",
    status: "Welcome Sent",
    riskLevel: "Low",
    email: "natalie.wong@email.com",
    phone: "0456 789 012",
    missingDocuments: 5,
    lastContacted: "2026-06-28",
    nextAction: "Awaiting initial document submission",
    notes: "",
    documents: [
      { id: "doc-023", name: "Signed Employment Contract", required: true, received: false },
      { id: "doc-024", name: "Tax File Number Declaration", required: true, received: false },
      { id: "doc-025", name: "Right to Work Evidence", required: true, received: false },
      { id: "doc-026", name: "Bank Details Form", required: true, received: false },
      { id: "doc-027", name: "Emergency Contact Form", required: false, received: false },
    ],
    communications: [
      {
        id: "com-005",
        type: "email",
        direction: "sent",
        subject: "Welcome to Pinnacle Group — Your Onboarding Pack",
        body: "Hi Natalie, we're thrilled to have you joining the team on 21 July. Please find your onboarding pack attached.",
        timestamp: "2026-06-28T09:00:00",
      },
    ],
  },
];

export const MOCK_APPROVALS: Approval[] = [
  {
    id: "app-001",
    clientId: "client-001",
    digitalEmployee: "AI Onboarding Assistant",
    actionType: "Reminder Email",
    relatedPerson: "Sarah Thompson",
    draftContent:
      "Hi Sarah, this is a friendly reminder that we still have 3 outstanding documents required before your start date on 7 July. Please submit your Tax File Number Declaration, Right to Work Evidence, and Safety Induction Certificate at your earliest convenience. If you need any assistance, please don't hesitate to reply to this email.",
    reason: "3 documents outstanding with start date 9 days away. Escalation reminder recommended.",
    status: "pending",
    createdAt: "2026-06-28T08:30:00",
  },
  {
    id: "app-002",
    clientId: "client-001",
    digitalEmployee: "AI Onboarding Assistant",
    actionType: "Escalation Alert",
    relatedPerson: "Priya Mehta",
    draftContent:
      "Hi Tom, I'm flagging that Priya Mehta starts this Monday 30 June and currently has 4 critical documents outstanding including her Tax File Number Declaration and Bank Details. Without these documents she cannot be paid correctly. I recommend contacting Priya directly today to resolve this before her start date.",
    reason: "Critical risk: employee starts in 2 days with 4 missing mandatory documents. Manager escalation required.",
    status: "pending",
    createdAt: "2026-06-28T08:35:00",
  },
  {
    id: "app-003",
    clientId: "client-001",
    digitalEmployee: "AI Growth Assistant",
    actionType: "Lead Follow-up Email",
    relatedPerson: "Mitchell Evans",
    relatedBusiness: "Evans Construction Group",
    draftContent:
      "Hi Mitchell, thank you for your enquiry about Axiploy's AI Onboarding Assistant. Based on what you shared, it sounds like you're managing a high volume of seasonal hires and finding the onboarding process time-consuming. I'd love to show you how we've helped similar businesses in construction reduce their onboarding admin by over 60%. Would you be available for a 30-minute call this week?",
    reason: "Lead submitted enquiry 48 hours ago with no follow-up. High intent signal based on enquiry content.",
    status: "pending",
    createdAt: "2026-06-28T09:00:00",
  },
  {
    id: "app-004",
    clientId: "client-001",
    digitalEmployee: "AI Admin Assistant",
    actionType: "Manager Report",
    relatedPerson: "David Chen",
    draftContent:
      "Weekly Onboarding Summary — Week ending 28 June 2026\n\nActive Onboardings: 12\nCompleted this week: 1 (Jake Morrison)\nAt Risk: 2 (Sarah Thompson, Priya Mehta)\nDocuments Outstanding: 12 across all active onboardings\n\nAction Required: Priya Mehta requires immediate attention — 4 documents outstanding with Monday start date.",
    reason: "Weekly manager report due. Summary compiled from onboarding activity this week.",
    status: "pending",
    createdAt: "2026-06-28T07:00:00",
  },
  {
    id: "app-005",
    clientId: "client-001",
    digitalEmployee: "AI Growth Assistant",
    actionType: "Re-engagement Email",
    relatedPerson: "Karen Briggs",
    relatedBusiness: "Briggs Labour Solutions",
    draftContent:
      "Hi Karen, it's been a while since we last spoke and I wanted to reach out as we've recently launched our AI Onboarding Assistant — which I think would be a great fit for your business given the volume of placements you manage. Would you be open to a quick catch-up to see what's new?",
    reason: "Client went cold 90 days ago. Re-engagement sequence triggered based on inactivity threshold.",
    status: "pending",
    createdAt: "2026-06-27T16:00:00",
  },
];

export const MOCK_ACTIVITY: ActivityEntry[] = [
  { id: "act-001", clientId: "client-001", digitalEmployee: "AI Onboarding Assistant", action: "Welcome email sent to Natalie Wong", result: "Email delivered successfully", status: "success", timestamp: "2026-06-28T09:02:00" },
  { id: "act-002", clientId: "client-001", digitalEmployee: "AI Growth Assistant", action: "New lead identified: Mitchell Evans — Evans Construction Group", result: "Lead added to pipeline, follow-up drafted", status: "info", timestamp: "2026-06-28T08:58:00" },
  { id: "act-003", clientId: "client-001", digitalEmployee: "AI Onboarding Assistant", action: "Critical risk flag raised: Priya Mehta — 4 documents missing, starts Monday", result: "Escalation sent to manager Tom Walsh", status: "warning", timestamp: "2026-06-28T08:35:00" },
  { id: "act-004", clientId: "client-001", digitalEmployee: "AI Admin Assistant", action: "Weekly manager report compiled for David Chen", result: "Awaiting approval before sending", status: "info", timestamp: "2026-06-28T07:00:00" },
  { id: "act-005", clientId: "client-001", digitalEmployee: "AI Onboarding Assistant", action: "Document reminder sent to Sarah Thompson", result: "Email delivered — 3 documents still outstanding", status: "warning", timestamp: "2026-06-27T10:00:00" },
  { id: "act-006", clientId: "client-001", digitalEmployee: "AI Onboarding Assistant", action: "Onboarding complete: Jake Morrison", result: "All 5 documents received and verified", status: "success", timestamp: "2026-06-26T14:30:00" },
  { id: "act-007", clientId: "client-001", digitalEmployee: "AI Admin Assistant", action: "38 emails processed and categorised", result: "14 tasks created, 6 reminders scheduled", status: "success", timestamp: "2026-06-26T12:00:00" },
  { id: "act-008", clientId: "client-001", digitalEmployee: "AI Growth Assistant", action: "Follow-up sent to 8 pipeline leads", result: "3 responses received — 1 meeting booked", status: "success", timestamp: "2026-06-26T10:00:00" },
  { id: "act-009", clientId: "client-001", digitalEmployee: "AI Growth Assistant", action: "Re-engagement sequence triggered: Karen Briggs — Briggs Labour Solutions", result: "Email drafted and awaiting approval", status: "info", timestamp: "2026-06-27T16:00:00" },
  { id: "act-010", clientId: "client-001", digitalEmployee: "AI Onboarding Assistant", action: "Tax File Number Declaration received from Marcus Rivera", result: "Document logged and checklist updated", status: "success", timestamp: "2026-06-24T11:20:00" },
];

export const MOCK_REPORTS: Report[] = [
  {
    id: "rep-001",
    clientId: "client-001",
    type: "Monthly Performance Report",
    period: "June 2026",
    status: "ready",
    createdAt: "2026-06-28T07:00:00",
    summary: {
      tasksCompleted: 428,
      hoursSaved: 74,
      issuesFlagged: 7,
      actionsTaken: 312,
      outstandingItems: 9,
      highlights: [
        "12 employees actively onboarding — 1 completed this month",
        "AI Growth Assistant identified 21 new leads",
        "Admin Assistant processed 38 emails saving estimated 12 hours",
        "2 critical risk onboardings flagged and escalated",
      ],
    },
  },
  {
    id: "rep-002",
    clientId: "client-001",
    type: "Weekly Onboarding Report",
    period: "Week ending 28 June 2026",
    status: "ready",
    createdAt: "2026-06-28T07:00:00",
    summary: {
      tasksCompleted: 94,
      hoursSaved: 18,
      issuesFlagged: 3,
      actionsTaken: 67,
      outstandingItems: 12,
      highlights: [
        "Jake Morrison onboarding complete",
        "Priya Mehta flagged as Critical — immediate action required",
        "Sarah Thompson reminder sent — 3 documents outstanding",
      ],
    },
  },
  {
    id: "rep-003",
    clientId: "client-001",
    type: "Growth Report",
    period: "June 2026",
    status: "generating",
    createdAt: "2026-06-28T08:00:00",
    summary: {
      tasksCompleted: 156,
      hoursSaved: 28,
      issuesFlagged: 2,
      actionsTaken: 98,
      outstandingItems: 8,
      highlights: [
        "21 new leads identified and added to pipeline",
        "8 follow-ups due this week",
        "4 opportunities awaiting approval",
      ],
    },
  },
];
