"use client";

import { useState } from "react";
import StatusPill from "@/components/portal/StatusPill";
import { MOCK_REPORTS, MOCK_METRICS, MOCK_USER } from "@/lib/mock-data";
import { BarChart2, Download, ChevronDown, ChevronUp, CheckCircle2, Clock, AlertTriangle, Activity, Calculator, Printer } from "lucide-react";
import type { Report } from "@/lib/types";

function ReportCard({ report }: { report: Report }) {
  const [expanded, setExpanded] = useState(false);

  function handlePrint() {
    const win = window.open("", "_blank");
    if (!win) return;
    win.document.write(`
      <html><head><title>${report.type} – ${report.period}</title>
      <style>
        body { font-family: sans-serif; padding: 40px; color: #111; }
        h1 { font-size: 24px; margin-bottom: 4px; }
        p { color: #555; font-size: 14px; }
        .grid { display: grid; grid-template-columns: repeat(5, 1fr); gap: 16px; margin: 24px 0; }
        .stat { background: #f5f5f5; border-radius: 8px; padding: 16px; text-align: center; }
        .stat strong { display: block; font-size: 22px; }
        .stat span { font-size: 11px; color: #777; }
        ul { padding-left: 20px; }
        li { margin-bottom: 8px; font-size: 14px; }
        .footer { margin-top: 40px; border-top: 1px solid #eee; padding-top: 16px; font-size: 12px; color: #999; }
      </style></head><body>
      <h1>${report.type}</h1>
      <p>${report.period} · Generated by Axiploy AI for ${MOCK_USER.clientName}</p>
      <div class="grid">
        <div class="stat"><strong>${report.summary.tasksCompleted}</strong><span>Tasks Completed</span></div>
        <div class="stat"><strong>${report.summary.hoursSaved}h</strong><span>Hours Saved</span></div>
        <div class="stat"><strong>${report.summary.issuesFlagged}</strong><span>Issues Flagged</span></div>
        <div class="stat"><strong>${report.summary.actionsTaken}</strong><span>Actions Taken</span></div>
        <div class="stat"><strong>${report.summary.outstandingItems}</strong><span>Outstanding</span></div>
      </div>
      <h2>Highlights</h2>
      <ul>${report.summary.highlights.map((h) => `<li>${h}</li>`).join("")}</ul>
      <div class="footer">Axiploy AI Workforce Platform · Confidential · ${new Date().toLocaleDateString("en-AU")}</div>
      </body></html>
    `);
    win.document.close();
    win.print();
  }

  return (
    <div className="glass rounded-2xl border border-white/[0.08] overflow-hidden">
      <div
        className="flex items-center justify-between p-5 cursor-pointer hover:bg-white/[0.02] transition-colors"
        onClick={() => setExpanded(!expanded)}
      >
        <div className="flex items-center gap-4">
          <div className="w-10 h-10 rounded-xl bg-accent-blue/10 flex items-center justify-center">
            <BarChart2 size={18} className="text-accent-blue" />
          </div>
          <div>
            <p className="text-text-primary font-medium text-sm">{report.type}</p>
            <p className="text-text-muted text-xs mt-0.5">{report.period}</p>
          </div>
        </div>
        <div className="flex items-center gap-3">
          <StatusPill status={report.status} />
          <button className="text-text-muted hover:text-text-primary transition-colors">
            {expanded ? <ChevronUp size={16} /> : <ChevronDown size={16} />}
          </button>
        </div>
      </div>

      {expanded && (
        <div className="border-t border-white/[0.06] p-5">
          <div className="grid grid-cols-2 md:grid-cols-5 gap-4 mb-5">
            {[
              { icon: CheckCircle2, label: "Tasks Completed", value: report.summary.tasksCompleted, colour: "text-emerald-400" },
              { icon: Clock, label: "Hours Saved", value: `${report.summary.hoursSaved}h`, colour: "text-accent-cyan" },
              { icon: AlertTriangle, label: "Issues Flagged", value: report.summary.issuesFlagged, colour: "text-amber-400" },
              { icon: Activity, label: "Actions Taken", value: report.summary.actionsTaken, colour: "text-accent-blue" },
              { icon: Clock, label: "Outstanding", value: report.summary.outstandingItems, colour: "text-text-muted" },
            ].map((m) => (
              <div key={m.label} className="bg-white/[0.03] rounded-xl p-4 text-center">
                <m.icon size={14} className={`${m.colour} mx-auto mb-2`} />
                <p className="font-heading font-bold text-text-primary text-xl">{m.value}</p>
                <p className="text-text-muted text-[10px] mt-0.5">{m.label}</p>
              </div>
            ))}
          </div>

          <div className="mb-4">
            <p className="text-text-muted text-xs font-medium mb-2">Highlights</p>
            <ul className="space-y-1.5">
              {report.summary.highlights.map((h) => (
                <li key={h} className="flex items-start gap-2 text-text-muted text-sm">
                  <CheckCircle2 size={13} className="text-accent-cyan shrink-0 mt-0.5" />
                  {h}
                </li>
              ))}
            </ul>
          </div>

          <button
            onClick={handlePrint}
            className="inline-flex items-center gap-2 px-4 py-2 rounded-full glass border border-white/[0.10] hover:border-accent-blue/30 hover:text-accent-blue text-text-muted text-xs font-medium transition-colors"
          >
            <Printer size={13} /> Export as PDF
          </button>
        </div>
      )}
    </div>
  );
}

function SavingsCalculator() {
  const [rate, setRate] = useState(35);
  const annualHours = MOCK_METRICS.hoursSaved * 12;
  const annualSaving = Math.round(annualHours * rate);

  return (
    <div className="glass rounded-2xl border border-white/[0.08] p-6 space-y-5">
      <div className="flex items-center gap-3">
        <div className="w-10 h-10 rounded-xl bg-emerald-500/10 flex items-center justify-center">
          <Calculator size={18} className="text-emerald-400" />
        </div>
        <div>
          <p className="text-text-primary font-medium text-sm">Time & Money Saved Calculator</p>
          <p className="text-text-muted text-xs mt-0.5">Estimate the financial value of your AI workforce</p>
        </div>
      </div>

      <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
        {[
          { label: "Hours saved this month", value: `${MOCK_METRICS.hoursSaved}h`, colour: "text-accent-cyan" },
          { label: "Projected annual hours", value: `${annualHours}h`, colour: "text-accent-blue" },
          { label: "Tasks automated", value: String(MOCK_METRICS.tasksCompleted), colour: "text-emerald-400" },
          { label: "Annual cost saving", value: `£${annualSaving.toLocaleString()}`, colour: "text-emerald-400" },
        ].map((m) => (
          <div key={m.label} className="bg-white/[0.03] rounded-xl p-4 text-center">
            <p className={`font-heading font-bold text-xl ${m.colour}`}>{m.value}</p>
            <p className="text-text-muted text-[10px] mt-1">{m.label}</p>
          </div>
        ))}
      </div>

      <div>
        <div className="flex items-center justify-between mb-2">
          <label className="text-text-muted text-xs">Average hourly labour cost</label>
          <span className="text-text-primary text-sm font-semibold">£{rate}/hr</span>
        </div>
        <input
          type="range"
          min={15}
          max={150}
          step={5}
          value={rate}
          onChange={(e) => setRate(Number(e.target.value))}
          className="w-full accent-accent-blue h-1.5 rounded-full"
        />
        <div className="flex justify-between text-[10px] text-text-muted/50 mt-1">
          <span>£15/hr</span>
          <span>£150/hr</span>
        </div>
      </div>

      <p className="text-xs text-text-muted/60 italic">
        Based on {MOCK_METRICS.hoursSaved} hours saved this month × 12 months × £{rate}/hr. Actual savings may vary.
      </p>
    </div>
  );
}

export default function ReportsPage() {
  return (
    <div className="space-y-6 max-w-3xl">
      <div>
        <h1 className="font-heading text-2xl font-bold text-text-primary">Reports</h1>
        <p className="text-text-muted text-sm mt-1">Performance summaries generated by your AI workforce.</p>
      </div>

      <SavingsCalculator />

      <div className="space-y-4">
        {MOCK_REPORTS.map((r) => <ReportCard key={r.id} report={r} />)}
      </div>
    </div>
  );
}
