"use client";

import { useState, useEffect } from "react";
import { BarChart2, ChevronDown, ChevronUp, CheckCircle2, Clock, AlertTriangle, Activity, Calculator, Printer } from "lucide-react";

interface Metrics {
  hoursSaved: number;
  tasksCompleted: number;
  activeOnboardings: number;
  completedOnboardings: number;
  actionsThisMonth: number;
  approvalsHandled: number;
  clientName: string;
}

function ReportCard({ title, period, metrics, clientName }: {
  title: string;
  period: string;
  metrics: Metrics;
  clientName: string;
}) {
  const [expanded, setExpanded] = useState(false);

  function handlePrint() {
    const win = window.open("", "_blank");
    if (!win) return;
    win.document.write(`
      <html><head><title>${title} – ${period}</title>
      <style>
        body { font-family: sans-serif; padding: 40px; color: #111; }
        h1 { font-size: 24px; margin-bottom: 4px; }
        p { color: #555; font-size: 14px; }
        .grid { display: grid; grid-template-columns: repeat(5, 1fr); gap: 16px; margin: 24px 0; }
        .stat { background: #f5f5f5; border-radius: 8px; padding: 16px; text-align: center; }
        .stat strong { display: block; font-size: 22px; }
        .stat span { font-size: 11px; color: #777; }
        .footer { margin-top: 40px; border-top: 1px solid #eee; padding-top: 16px; font-size: 12px; color: #999; }
      </style></head><body>
      <h1>${title}</h1>
      <p>${period} · Generated by Axiploy AI for ${clientName}</p>
      <div class="grid">
        <div class="stat"><strong>${metrics.tasksCompleted}</strong><span>Tasks Completed</span></div>
        <div class="stat"><strong>${metrics.hoursSaved}h</strong><span>Hours Saved</span></div>
        <div class="stat"><strong>${metrics.activeOnboardings}</strong><span>Active Onboardings</span></div>
        <div class="stat"><strong>${metrics.actionsThisMonth}</strong><span>AI Actions This Month</span></div>
        <div class="stat"><strong>${metrics.approvalsHandled}</strong><span>Approvals Handled</span></div>
      </div>
      <div class="footer">Axiploy AI Workforce Platform · Confidential · ${new Date().toLocaleDateString("en-AU")}</div>
      </body></html>
    `);
    win.document.close();
    win.print();
  }

  return (
    <div className="glass rounded-2xl border border-white/[0.08] overflow-hidden">
      <div
        className="flex items-center justify-between p-5 cursor-pointer hover:bg-white/[0.02] transition-colors"
        onClick={() => setExpanded(!expanded)}
      >
        <div className="flex items-center gap-4">
          <div className="w-10 h-10 rounded-xl bg-accent-blue/10 flex items-center justify-center">
            <BarChart2 size={18} className="text-accent-blue" />
          </div>
          <div>
            <p className="text-text-primary font-medium text-sm">{title}</p>
            <p className="text-text-muted text-xs mt-0.5">{period}</p>
          </div>
        </div>
        <div className="flex items-center gap-3">
          <span className="text-[10px] px-2.5 py-1 rounded-full bg-emerald-500/10 text-emerald-400 border border-emerald-500/20 font-medium">Ready</span>
          <button className="text-text-muted hover:text-text-primary transition-colors">
            {expanded ? <ChevronUp size={16} /> : <ChevronDown size={16} />}
          </button>
        </div>
      </div>

      {expanded && (
        <div className="border-t border-white/[0.06] p-5">
          <div className="grid grid-cols-2 md:grid-cols-5 gap-4 mb-5">
            {[
              { icon: CheckCircle2, label: "Tasks Completed", value: metrics.tasksCompleted, colour: "text-emerald-400" },
              { icon: Clock, label: "Hours Saved", value: `${metrics.hoursSaved}h`, colour: "text-accent-cyan" },
              { icon: Activity, label: "AI Actions", value: metrics.actionsThisMonth, colour: "text-accent-blue" },
              { icon: CheckCircle2, label: "Approvals Handled", value: metrics.approvalsHandled, colour: "text-accent-blue" },
              { icon: AlertTriangle, label: "Active Onboardings", value: metrics.activeOnboardings, colour: "text-amber-400" },
            ].map((m) => (
              <div key={m.label} className="bg-white/[0.03] rounded-xl p-4 text-center">
                <m.icon size={14} className={`${m.colour} mx-auto mb-2`} />
                <p className="font-heading font-bold text-text-primary text-xl">{m.value}</p>
                <p className="text-text-muted text-[10px] mt-0.5">{m.label}</p>
              </div>
            ))}
          </div>
          <button
            onClick={handlePrint}
            className="inline-flex items-center gap-2 px-4 py-2 rounded-full glass border border-white/[0.10] hover:border-accent-blue/30 hover:text-accent-blue text-text-muted text-xs font-medium transition-colors"
          >
            <Printer size={13} /> Export as PDF
          </button>
        </div>
      )}
    </div>
  );
}

function SavingsCalculator({ hoursSaved, tasksCompleted }: { hoursSaved: number; tasksCompleted: number }) {
  const [rate, setRate] = useState(35);
  const annualHours = hoursSaved * 12;
  const annualSaving = Math.round(annualHours * rate);

  return (
    <div className="glass rounded-2xl border border-white/[0.08] p-6 space-y-5">
      <div className="flex items-center gap-3">
        <div className="w-10 h-10 rounded-xl bg-emerald-500/10 flex items-center justify-center">
          <Calculator size={18} className="text-emerald-400" />
        </div>
        <div>
          <p className="text-text-primary font-medium text-sm">Time & Money Saved Calculator</p>
          <p className="text-text-muted text-xs mt-0.5">Estimate the financial value of your AI workforce</p>
        </div>
      </div>

      <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
        {[
          { label: "Hours saved this month", value: `${hoursSaved}h`, colour: "text-accent-cyan" },
          { label: "Projected annual hours", value: `${annualHours}h`, colour: "text-accent-blue" },
          { label: "Tasks automated", value: String(tasksCompleted), colour: "text-emerald-400" },
          { label: "Annual cost saving", value: `£${annualSaving.toLocaleString()}`, colour: "text-emerald-400" },
        ].map((m) => (
          <div key={m.label} className="bg-white/[0.03] rounded-xl p-4 text-center">
            <p className={`font-heading font-bold text-xl ${m.colour}`}>{m.value}</p>
            <p className="text-text-muted text-[10px] mt-1">{m.label}</p>
          </div>
        ))}
      </div>

      <div>
        <div className="flex items-center justify-between mb-2">
          <label className="text-text-muted text-xs">Average hourly labour cost</label>
          <span className="text-text-primary text-[13px] font-semibold">£{rate}/hr</span>
        </div>
        <input
          type="range" min={15} max={150} step={5} value={rate}
          onChange={(e) => setRate(Number(e.target.value))}
          className="w-full accent-accent-blue h-1.5 rounded-full"
        />
        <div className="flex justify-between text-[10px] text-text-muted/50 mt-1">
          <span>£15/hr</span><span>£150/hr</span>
        </div>
      </div>

      <p className="text-xs text-text-muted/60 italic">
        Based on {hoursSaved} hours saved this month × 12 months × £{rate}/hr. Actual savings may vary.
      </p>
    </div>
  );
}

export default function ReportsPage() {
  const [metrics, setMetrics] = useState<Metrics | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetch("/api/portal/reports/metrics")
      .then((r) => r.json())
      .then((d) => setMetrics(d))
      .catch(() => {})
      .finally(() => setLoading(false));
  }, []);

  const now = new Date();
  const monthName = now.toLocaleString("en-AU", { month: "long", year: "numeric" });

  return (
    <div className="space-y-6 max-w-3xl">
      <div>
        <h1 className="font-heading text-xl font-bold text-text-primary">Reports</h1>
        <p className="text-text-muted text-[13px] mt-1">Performance summaries generated by your AI workforce.</p>
      </div>

      {loading ? (
        <div className="py-10 text-center text-text-muted text-[13px]">Loading reports…</div>
      ) : metrics ? (
        <>
          <SavingsCalculator hoursSaved={metrics.hoursSaved} tasksCompleted={metrics.tasksCompleted} />
          <div className="space-y-4">
            <ReportCard
              title="Monthly Performance Report"
              period={monthName}
              metrics={metrics}
              clientName={metrics.clientName}
            />
            <ReportCard
              title="Onboarding Summary"
              period={`${metrics.completedOnboardings} completed · ${metrics.activeOnboardings} active`}
              metrics={metrics}
              clientName={metrics.clientName}
            />
          </div>
        </>
      ) : (
        <div className="glass rounded-2xl p-10 text-center border border-white/[0.06]">
          <BarChart2 size={28} className="text-text-muted/30 mx-auto mb-3" />
          <p className="text-text-primary text-[13px] font-medium">No report data yet</p>
          <p className="text-text-muted text-xs mt-1">Reports will generate once your AI employees start working.</p>
        </div>
      )}
    </div>
  );
}
